<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * @todo Write general description for this enumeration
 */
class ActivateEnum
{
    /**
     * TODO: Write general description for this element
     */
    const MACTIVATE = 1;

    /**
     * TODO: Write general description for this element
     */
    const DEACTIVATE = 0;
}
