<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class AudioUrlEnum
{
    /**
     * mp3 file
     */
    const MP3 = "mp3";

    /**
     * wav file
     */
    const WAV = "wav";
}
