<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * The direction the audio effect should be placed on. If IN, the effects will occur on the incoming
 * audio stream. If OUT, the effects will occur on the outgoing audio stream.
 */
class AudioDirectionEnum
{
    /**
     * TODO: Write general description for this element
     */
    const IN = "in";

    /**
     * TODO: Write general description for this element
     */
    const OUT = "out";
}
