<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * Audio Format file type mp3 or wav
 */
class AudioFormatEnum
{
    /**
     * mp3 file
     */
    const MP3 = "mp3";

    /**
     * wav file
     */
    const WAV = "wav";
}
