<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * Audio Direction
 */
class AudioDirection29Enum
{
    /**
     * TODO: Write general description for this element
     */
    const IN = "in";

    /**
     * TODO: Write general description for this element
     */
    const OUT = "out";
}
