<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * Play DTMF Direction & in play audio & sendDigit
 */
class DirectionEnum
{
    /**
     * in direction
     */
    const IN = "in";

    /**
     * out direction
     */
    const OUT = "out";

    /**
     * both
     */
    const BOTH = "both";
}
