<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * The leg of the call audio will be played to
 */
class DirectionEnum
{
    /**
     * TODO: Write general description for this element
     */
    const IN = "in";

    /**
     * TODO: Write general description for this element
     */
    const OUT = "out";

    /**
     * TODO: Write general description for this element
     */
    const BOTH = "both";
}
