<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Error implements JsonSerializable
{
    /**
     * Error Response Code
     * @required
     * @maps Code
     * @var string $code public property
     */
    public $code;

    /**
     * Error Response Message
     * @required
     * @maps Message
     * @var string $message public property
     */
    public $message;

    /**
     * Detailed Error Info
     * @required
     * @maps MoreInfo
     * @var array $moreInfo public property
     */
    public $moreInfo;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $code     Initialization value for $this->code
     * @param string $message  Initialization value for $this->message
     * @param array  $moreInfo Initialization value for $this->moreInfo
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->code     = func_get_arg(0);
            $this->message  = func_get_arg(1);
            $this->moreInfo = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Code']     = $this->code;
        $json['Message']  = $this->message;
        $json['MoreInfo'] = $this->moreInfo;

        return $json;
    }
}
