<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Errors implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps Error
     * @var \YtelAPIV3Lib\Models\Error[] $error public property
     */
    public $error;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $error Initialization value for $this->error
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->error = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Error'] = $this->error;

        return $json;
    }
}
