<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

use JsonSerializable;

/**
 *Error Structure Model
 */
class Errors implements JsonSerializable
{
    /**
     * Error Description
     * @required
     * @maps Error
     * @var \YtelAPILib\Models\Error[] $error public property
     */
    public $error;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $error Initialization value for $this->error
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->error = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['Error'] = $this->error;

        return $json;
    }
}
