<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * Format of the recording file. Can be .mp3 or .wav
 */
class FileformatEnum
{
    /**
     * TODO: Write general description for this element
     */
    const MP3 = "mp3";

    /**
     * TODO: Write general description for this element
     */
    const WAV = "wav";
}
