<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * Specify the audio file you want to play when the called party picks up the call
 */
class GroupConfirmFileEnum
{
    /**
     * TODO: Write general description for this element
     */
    const MP3 = "mp3";

    /**
     * TODO: Write general description for this element
     */
    const WAV = "wav";
}
