<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * Types Of Method
 */
class HttpActionEnum
{
    /**
     * Get type
     */
    const GET = "GET";

    /**
     * Post Type
     */
    const POST = "POST";
}
