<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * How Message360 should handle the receiving numbers voicemail machine
 */
class IfMachine32Enum
{
    /**
     * TODO: Write general description for this element
     */
    const CONTINUE_ = "continue";

    /**
     * TODO: Write general description for this element
     */
    const HANGUP = "hangup";
}
