<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * Interrupted Call Status
 */
class InterruptedCallStatusEnum
{
    /**
     * Interrupt Call will be cancel
     */
    const CANCELED = "canceled";

    /**
     * Interrupt Call is complete
     */
    const COMPLETED = "completed";
}
