<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class MActivateEnum
{
    /**
     * TODO: Write general description for this element
     */
    const ACTIVATE = 1;

    /**
     * TODO: Write general description for this element
     */
    const DEACTIVATE = 0;
}
