<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * @todo Write general description for this enumeration
 */
class MergeNumber40Enum
{
    /**
     * TODO: Write general description for this element
     */
    const DELETE = 0;

    /**
     * TODO: Write general description for this element
     */
    const MERGE = 1;
}
