<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * Choose sub account either merge or delete
 */
class MergeNumberStatusEnum
{
    /**
     * TODO: Write general description for this element
     */
    const DELETE = 0;

    /**
     * TODO: Write general description for this element
     */
    const MERGE = 1;
}
