<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * 0 to delete or 1 to merge numbers to parent account.
 */
class MergeNumberEnum
{
    /**
     * TODO: Write general description for this element
     */
    const ENUM_0 = 0;

    /**
     * TODO: Write general description for this element
     */
    const ENUM_1 = 1;
}
