<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * Phone Number Type All,SMS or Voice
 */
class NumberType24Enum
{
    /**
     * Get all phone Number type
     */
    const ALL = "all";

    /**
     * Get only voice number type
     */
    const VOICE = "voice";

    /**
     * Get Only SMs number type
     */
    const SMS = "sms";
}
