<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * @todo Write general description for this enumeration
 */
class Numbertype16Enum
{
    /**
     * Get all phone Number type
     */
    const ALL = "all";

    /**
     * Get only voice number type
     */
    const VOICE = "voice";

    /**
     * Get Only SMs number type
     */
    const SMS = "sms";
}
