<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * @todo Write general description for this enumeration
 */
class ProductCode27Enum
{
    /**
     * TODO: Write general description for this element
     */
    const ALL = 0;

    /**
     * TODO: Write general description for this element
     */
    const ENUM_1 = 1;

    /**
     * TODO: Write general description for this element
     */
    const ENUM_2 = 2;

    /**
     * TODO: Write general description for this element
     */
    const ENUM_3 = 3;

    /**
     * TODO: Write general description for this element
     */
    const ENUM_4 = 4;

    /**
     * TODO: Write general description for this element
     */
    const TRANSCRIPTION = 5;

    /**
     * TODO: Write general description for this element
     */
    const EMAIL = 6;

    /**
     * TODO: Write general description for this element
     */
    const CONFERENCE = 7;

    /**
     * TODO: Write general description for this element
     */
    const CARRIER = 8;

    /**
     * TODO: Write general description for this element
     */
    const ENUM_9 = 9;

    /**
     * TODO: Write general description for this element
     */
    const ENUM_10 = 10;

    /**
     * TODO: Write general description for this element
     */
    const ENUM_11 = 11;

    /**
     * TODO: Write general description for this element
     */
    const ENUM_12 = 12;

    /**
     * TODO: Write general description for this element
     */
    const ENUM_13 = 13;
}
