<?php
/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPILib\Models;

/**
 * send email TEXT or HTML format
 */
class SendEmailAsEnum
{
    /**
     * Email send as text format
     */
    const TEXT = "text";

    /**
     * Email send as HTML format
     */
    const HTML = "html";
}
