<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * The state of the transcription.
 */
class Status12Enum
{
    /**
     * TODO: Write general description for this element
     */
    const INPROGRESS = "inprogress";

    /**
     * TODO: Write general description for this element
     */
    const SUCCESS = "success";

    /**
     * TODO: Write general description for this element
     */
    const FAILURE = "failure";
}
