<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * Status to set the in-progress call to
 */
class StatusEnum
{
    /**
     * TODO: Write general description for this element
     */
    const CANCELED = "canceled";

    /**
     * TODO: Write general description for this element
     */
    const COMPLETED = "completed";
}
