<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * @todo Write general description for this enumeration
 */
class Type36Enum
{
    /**
     * Email send as text format
     */
    const TEXT = "text";

    /**
     * Email send as HTML format
     */
    const HTML = "html";
}
