<?php
/*
 * YtelAPIV3Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace YtelAPIV3Lib\Models;

/**
 * Specifies the type of email to be sent
 */
class TypeEnum
{
    /**
     * TODO: Write general description for this element
     */
    const TEXT = "text";

    /**
     * TODO: Write general description for this element
     */
    const HTML = "html";
}
